In [9]:
import pandas as pd
df= pd.read_csv("ass2.csv")
df
import warnings
warnings.filterwarnings("ignore")

In [10]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
x

      CGPA Communication Aptitude Programming_skill
0     High          Good     High              Good
1   Medium          Good     High              Good
2      Low           Bad      Low              Good
3      Low          Good      Low               Bad
4     High          Good     High               Bad
5     High          Good     High              Good
6   Medium           Bad      Low               Bad
7   Medium           Bad      Low              Good
8     High           Bad     High              Good
9   Medium          Good     High              Good
10     Low           Bad     High               Bad
11     Low           Bad     High               Bad
12  Medium          Good     High               Bad
13     Low          Good      Low              Good
14    High           Bad      Low               Bad

In [11]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
y

0     Yes
1     Yes
2      No
3      No
4     Yes
5     Yes
6      No
7      No
8     Yes
9     Yes
10     No
11     No
12    Yes
13     No
14     No
Name: Job_offered, dtype: object

In [12]:
x['CGPA']=x['CGPA'].map({'Low':1,'Medium':2,'High':3})
x['Communication']=x['Communication'].map({'Good':1,'Bad':2})
x['Aptitude']=x['Aptitude'].map({'Low':1,'High':2})
x['Programming_skill']=x['Programming_skill'].map({'Good':1,'Bad':2})
x

    CGPA  Communication  Aptitude  Programming_skill
0      3              1         2                  1
1      2              1         2                  1
2      1              2         1                  1
3      1              1         1                  2
4      3              1         2                  2
5      3              1         2                  1
6      2              2         1                  2
7      2              2         1                  1
8      3              2         2                  1
9      2              1         2                  1
10     1              2         2                  2
11     1              2         2                  2
12     2              1         2                  2
13     1              1         1                  1
14     3              2         1                  2

In [13]:
from sklearn.tree import DecisionTreeClassifier
data = DecisionTreeClassifier()
data.fit(x,y)
data.predict([[1,2,1,2]])

array(['No'], dtype=object)